# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6c9e0585a854eb882a6c3dd680837e43d73323bbcd7f790badce5359b7a1f7f6be3a43a2a9badbff062d304938022c76a196989f9a0c6f829458211903c643a

test:
  secret_key_base: d194fcecd5123fdaaef71e6533b54157182aeaf5b609f68117471a66ed58acf0a25816510a1600607f8b1dd51330158dca9d61f92c03c716d4a5ed425214364c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
